### ISSUE TITLE
Game crashes when bonemealing oak saplings on mud

### ISSUE THREAD

**Issue by Luigipunch** [0rc1nus/GoodEnding#3]
When attempting to grow oak saplings on mud (to get the muddy oak tree), the game freezes for a second then crashes. 
[latest.log](https://github.com/0rc1nus/GoodEnding/files/10251935/latest.log)

In a different instance with ~50 mods, the log was spammed with the following block of text literally hundreds of thousands of times.

	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.2.0/net.minecraftforge.event.ForgeEventFactory.blockGrowFeature(ForgeEventFactory.java:627)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.grower.AbstractTreeGrower.m_213817_(AbstractTreeGrower.java:28)
	at TRANSFORMER/goodending@1.19.2-1.0.0/net.orcinus.goodending.events.MiscEvents.onSaplingGrow(MiscEvents.java:70)
	at TRANSFORMER/goodending@1.19.2-1.0.0/net.orcinus.goodending.events.__MiscEvents_onSaplingGrow_SaplingGrowTreeEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.2.0/net.minecraftforge.event.ForgeEventFactory.blockGrowFeature(ForgeEventFactory.java:627)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.grower.AbstractTreeGrower.m_213817_(AbstractTreeGrower.java:28)
	at TRANSFORMER/goodending@1.19.2-1.0.0/net.orcinus.goodending.events.MiscEvents.onSaplingGrow(MiscEvents.java:70)
	at TRANSFORMER/goodending@1.19.2-1.0.0/net.orcinus.goodending.events.__MiscEvents_onSaplingGrow_SaplingGrowTreeEvent.invoke(.dynamic)

**Comment by 0rc1nus** [comment]
Fixed in Good Ending 1.0.1
